In [1]:
import joblib 
tk = joblib.load('tokenizer.pkl')
xs, ys = joblib.load('Im-data.pkl')

In [2]:
import tensorflow as tf

In [4]:
lm = tf.keras.models.load_model('lm.krs')

In [5]:
x = xs[0]
y = ys[0]

In [6]:
x

array([21,  7, 20, 80])

In [7]:
y

17

In [8]:
[tk.index_word[i] for i in x]

['on', 'this', 'one', 'its']

In [9]:
tk.index_word[17]

'as'

In [14]:
x.shape

(4,)

In [15]:
# 신경망은 한꺼번에 여러개의 데이터를 받는것을 전제로 만들어져 있기 때문에 (1,4) 형태로 만들어줘야함 
xs[0:1]

array([[21,  7, 20, 80]])

In [21]:
logit = lm.predict(xs[0:1].astype('float32'))

In [23]:
logit.shape

(1, 2001)

In [24]:
# 모델을 만들때 softmax를 안해줬기 때문에 지금 확률이 아님 
# 즉 소프트맥스 함수에 넣어줘야함 
logit

array([[-4.063027 ,  3.9206908,  3.2857997, ..., -4.13777  , -3.9701293,
        -4.087406 ]], dtype=float32)

In [25]:
p = tf.nn.softmax(logit).numpy()

In [26]:
p

array([[3.2570195e-05, 9.5522352e-02, 5.0626200e-02, ..., 3.0224544e-05,
        3.5740894e-05, 3.1785774e-05]], dtype=float32)

In [28]:
p[0, 17]

0.007913981

In [29]:
np.argmax(p)

1

In [30]:
p[0,1]

0.09552235